openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0.1
servers:
  - url: http://localhost:8082
    description: Generated server url
paths:
  /api/v1/autotransport/quote-order-bff/rates:
    get:
      tags:
        - quote-handler
      operationId: getQuotes
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Submission'
components:
  schemas:
    ResponseError:
      type: object
      properties:
        status:
          type: string
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        message:
          type: string
        errors:
          type: array
          items:
            type: string
        url:
          type: string
    Quote:
      type: object
      properties:
        quoteId:
          type: integer
          format: int64
        shipper:
          $ref: '#/components/schemas/QuoteAddress'
        consignee:
          $ref: '#/components/schemas/QuoteAddress'
        shipmentDetails:
          $ref: '#/components/schemas/ShipmentDetails'
        isInsured:
          type: boolean
        insurance:
          $ref: '#/components/schemas/Insurance'
    QuoteAddress:
      required: [Country, postalZipCode, locationType]
      type: object
      properties:
        country:
          type: string
        postalZipCode:
          type: string
        dateRange:
          type: string
        locationType:
          $ref: '#/components/schemas/LocationType'
    ShipmentDetails:
      required: [ hazMat, docOnly, freezeProtect ]
      type: object
      properties:
        commodityId:
          type: integer
          format: int64
        numberPieces:
          type: number
        shipmentType:
          $ref: '#/components/schemas/ShipmentCategory'
        packaging:
          $ref: '#/components/schemas/Packaging'
        unitCount:
          type: number
        weight:
          type: number
        totalWeight:
          type: number
        length:
          type: integer
          format: int32
        width:
          type: integer
          format: int32
        minHeight:
          type: integer
          format: int32
        maxHeight:
          type: integer
          format: int32
        isHazMat:
          type: boolean
        hazMat:
          $ref: '#/components/schemas/HazMat'
        emergencyTel:
          type: string
          maxLength: 10
          pattern: '^\d{10}$'
        emergencyContact:
          type: string
          maxLength: 50
        hsCode:
          type: string
          pattern: '^\d{10}'
        nmfc:
          type: string
          pattern: '^\d{6}'
        freightClass:
          type: string
          pattern: '^\d{3}'
        freightSubClass:
          type: string
          pattern: '^\d{1}'
        isFreezeProtect:
          type: boolean
        isTempControl:
          type: boolean
        tempUnit:
          $ref: '#/components/schemas/Temperature'
        tempMin:
          type: integer
          format: int32
        tempMax:
          type: integer
          format: int32
        docOnly:
          type: boolean

    Temperature:
      type: string
      enum:
        - F
        - C
    LocationType:
      type: string
      enum:
        - BUS
        - RES_APP
        - RES_HOU
        - OTR_JS
        - OTR_CC
        - OTR_OB
        - OTR_HTL
        - OTR_SHL
    Packaging:
      type: string
      enum:
        - BOX   #Boxes
        - BAG   #Bags
        - BAL   #Bales
    ShipmentCategory:
      type: string
      enum:
        - LTR   #letter
        - PCK   #pack
        - PCL   #parcel
        - SKD   #Palet / skid
        - CRT   #Crate
        - BDL   #Bundle
        - RLL   #Roll
        - FSD   #Full truck palet
        - FFL   #Full truck floor
    HazMat:
      type: object
      properties:
        hazmatId:
          type: integer
          format: int64
        hazmatClass:
          type: string
        hazmatSubClass:
          type: string
        un:
          type: string
        packageGroup:
          type: string
    Insurance:
      type: object
      properties:
        totalCostValue:
          type: number
        currency:
          type: string
        insuranceType:
          type: string
    Submission:
      type: object
      properties:
        price:
          type: number